---
routes:
  ^/app01.*\z:
    headers:
      in:
        - Content-Type
        - Accepts
        - Host
      out:
        - Content-Type
    backends:
      - http://localhost:1111
  ^/app02.*\z:
    headers:
      in:
        - Content-Type
        - Accepts
        - Host
      out:
        - Content-Type
    backends:
      - http://localhost:2222
  ^/app03.*\z:
    headers:
      in:
        - Content-Type
        - Accepts
        - Host
      out:
        - Content-Type
    backends:
      - http://localhost:3333
  ^/app04.*\z:
    headers:
      in:
        - Content-Type
        - Accepts
        - Host
      out:
        - Content-Type
    backends:
      - http://localhost:4444
